# pppixiv
# ${VERSION} 占位符由面板在安装时替换
version: "3"

services:
  pppixiv:
    image: godmountain/pppixiv:${VERSION}
    container_name: pppixiv
    volumes:
      - ./Illusts:/APP/Illusts
    ports:
      - "5000:5000"
    environment:
      - username=${username}
      - password=${password}
      - port=5000
    restart: unless-stopped
