# NocoDB
# ${VERSION} 占位符由面板在安装时替换
version: "3"

services:
  nocodb:
    image: nocodb/nocodb:${VERSION}
    container_name: nocodb
    volumes:
      - ./data:/usr/app/data
    ports:
      - "8080:8080"
    environment:
      - NC_DB=${NC_DB}
    restart: unless-stopped
