# Watchtower - 容器自动更新
version: "3"

services:
  watchtower:
    image: containrrr/watchtower:${VERSION}
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
