# Redis
# ${VERSION} 占位符由面板在安装时替换
version: "3"

services:
  redis:
    image: redis:${VERSION}
    container_name: redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
